repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: local
    hooks:
      - id: ruff-check
        name: run ruff check
        entry: bash -c "cd tools && rye run ruff check . --fix --config pyproject.toml"
        language: system
        pass_filenames: false
      - id: ruff-format
        name: run ruff format
        entry: bash -c "cd tools && rye run ruff format . --config pyproject.toml"
        language: system
        pass_filenames: false
      - id: mypy
        name: run mypy
        entry: bash -c "cd tools && rye run mypy --strict commands"
        language: system
        pass_filenames: false
        types:
          - python
